services:
  agentbox:
    build:
      context: .
      args:
        AGENTBOX_BUILD_REVISION: ${AGENTBOX_BUILD_REVISION:-unknown}
        AGENTBOX_BUILD_SOURCE: ${AGENTBOX_BUILD_SOURCE:-https://github.com/sloikodavid/agentbox}
        AGENTBOX_BUILD_VERSION: ${AGENTBOX_BUILD_VERSION:-unknown}
    environment:
      - PORT=${PORT:-8080}
      - AGENTBOX_VOLUME_PATH=${AGENTBOX_VOLUME_PATH:-/data}
      - AGENTBOX_WORKSPACE_PATH
      - TZ
      - AGENTBOX_BIND_ADDRESS
      - AGENTBOX_AUTH
      - AGENTBOX_PASSWORD=12345
      - AGENTBOX_HASHED_PASSWORD
      - AGENTBOX_PUBLIC_URL
      - AGENTBOX_PUBLIC_PROXY_URL_TEMPLATE
      - AGENTBOX_TRUSTED_PROXY_HOPS
      - AGENTBOX_DISABLE_METRICS
      - AGENTBOX_DISABLE_FILE_DOWNLOADS
      - AGENTBOX_DISABLE_FILE_UPLOADS
      - AGENTBOX_TLS_KEY_PATH
      - AGENTBOX_TLS_CERT_PATH
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - mydata:${AGENTBOX_VOLUME_PATH:-/data}

volumes:
  mydata:
